;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ignore
        meow-append
        meow-expand-1
        meow-insert
        meow-insert-exit
        meow-next
        meow-prev
        meow-right
        ))

(setq mc/cmds-to-run-once
      '(
        meow-left
        mouse-set-secondary
        ))
